### ISSUE TITLE
Upgrade to Android-Components 0.32.0

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-android#189]
This task will involve updating the use of the `fxa-client` library to reflect breaking API changes, as well as adding specs for the `AccountStore`.

## Todo

* [x] update gradle dependencies
* [x] make changes where breakage occurs
* [x] revisit `app/lint-baseline.xml`

Depends on mozilla-mobile/android-components#1332

**Comment by sashei** [comment]
I've updated this issue to be a-c version `0.31.0` because we need them to remove the references to `kotlinx.coroutines.experimental` from the compiled libraries before we can integrate them with the new version of Kotlin & the coroutine library.
