### ISSUE TITLE
Provide credentials via Autofill when available

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-android#215]
### Acceptance Criteria

Lockbox-stored credentials are displayed on autofill-enabled pages when available. Selecting credentials fills the appropriate fields.

_Note_: This story does not deal with lock state. Provide credentials regardless of whether the app is locked or not.

### Engineering notes

Handle incoming [FillRequests](https://developer.android.com/reference/android/service/autofill/FillRequest) and parse the [FillContext](https://developer.android.com/reference/android/service/autofill/FillContext) to provide a FillCallback result of either all matching results or `null` if there are none.

### Tasks
- [x] Parse `FillRequest` for username and password fields
- [x] Parse domain out of requesting app package name
- [x] Search credentials for entries matching domain
- [x] Display both username and domain for entry in autofill UI

### Visual Design

**InVision**
Initial (1 entry): https://mozilla.invisionapp.com/share/3SN35UHWJDX#/317564412_Autofill_-_App_-_Initial
Initial (multiple entries): https://mozilla.invisionapp.com/share/3SN35UHWJDX#/317564409_Autofill_-_App_-_Initial_-multiple_Entries-
Filled: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/317564408_Autofill_-_App_-_Filled

**Zeplin**
Initial (1 entry): https://zpl.io/2pBe6lE
Initial (multiple entries): https://zpl.io/aNo8g9v

Depends on #214
