### ISSUE TITLE
Signing in for the first time (Signing in and authenticating with FxA)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#22]
## Acceptance criteria
* Sign in should happen within the app view

## Tasks
- [x] [Request](https://bugzilla.mozilla.org/show_bug.cgi?id=1499481) OAuth client be provisioned ([Details](https://github.com/mozilla-lockbox/lockbox-android/issues/22#issuecomment-433131989))
- [x] Implement AccountStore using `service-firefox-accounts`
- [x] FxA login with `cancel` button

### Visual Design

**InVision**
FxA Auth (email first flow): https://mozilla.invisionapp.com/share/3SN35UHWJDX#/311586971_FxA_-_Email

**Zeplin**
FxA Auth (email first flow): https://zpl.io/blpW3DG

**Comment by linuxwolf** [comment]
Request to provision OAuth client credentials tracked via [bugzilla 1499481](https://bugzilla.mozilla.org/show_bug.cgi?id=1499481)

**Comment by sashei** [comment]
Some initial / storage work in #151

**Comment by linuxwolf** [comment]
OAuth client provisioned:

```

{
  "id": "e7ce535d93522896",
  "name": "Firefox Lockbox for Android",
  "redirectUri": "https://lockbox.firefox.com/fxa/android-redirect.html",
  "canGrant": true,
  "trusted": true,
  "allowedScopes": "https://identity.mozilla.com/apps/lockbox
https://identity.mozilla.com/apps/oldsync",
  "publicClient": true
}
```
