### ISSUE TITLE
Scope and run accessibility test plan a first time

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#44]
Depends on #160

- [x] first run and document findings against accessibility scanner #200 #201 
- [x] first run and document findings while using TalkBack #223 
- [x] first run and document findings from adjusting font size 🆗 
- [x] document test plan (incorporate the existing accessibility doc stuff) #224 
- re run the test plan #225

**Comment by devinreams** [comment]
Updated original description above with the done items (accesibility scanner, TalkBack) and todos (dynamic font size, document plan, run the tests again).

**Comment by devinreams** [comment]
I just did a quick run through with the font size adjuster/setting on Android 8.0 and everything looked ok:

- nav bar
- drawer
- list view
- item view
- search/filter
- settings screen
- account screen

Since there were no glaring problems at this point (maybe minor improvements) and the UI is still yet to be finalized and polished, I’ll mark this as “OK” and done for now but to revisit again before launch.
